### ISSUE TITLE
please make a GULP plugin

### ISSUE THREAD

**Issue by yairEO** [jjt/grunt-lodash-autobuild#5]
it would be very nice of you :)

**Comment by jjt** [comment]
I actually just thought about this a month ago. Instead of making another plugin though, I just use this command to compile my Lo-Dash:

`lodash include=$(ack '_\.(\w*)' -h --output '$1' | sort -u | tr '\n' ',')`

More about it in an [article I wrote](http://jjt.io/2014/07/18/analyzing-source-files-to-automatically-create-custom-lo-dash-builds-in-73-characters/). Since this works well for me I don't see myself making a plugin, but thanks for the idea!
